name: itch.io

on:
  workflow_run:
    workflows: [Release]
    types: [completed]

jobs:
  itch-io:
    uses: cxreiff/github_workflows/.github/workflows/rust_release_itchio.yml@main
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    secrets:
      DEDICATED_TOKEN: ${{ secrets.DEDICATED_TOKEN }}
      BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
    with:
      itch_target: cxreiff/lifecycler
      workflow_run_id: ${{ github.event.workflow_run.id }}

